<?php

return [
    'categories' => [
        [
            'label' => 'Tất cả',
            'value' => null,
        ],
        [
            'label' => 'Hoạt động công ty',
            'value' => 'company-activity',
        ],
        [
            'label' => 'Thông báo tuyển dụng',
            'value' => 'recruitment',
        ],
    ],

    'articles' => [
        [
            'id' => 'n1',
            'slug' => 'giai-pickleball-mo-rong-2025',
            'title' => 'Giải Pickleball Công ty Xi măng Cẩm Phả mở rộng năm 2025 – Khi thể thao là cầu nối gắn kết và hợp tác trong công việc',
            'excerpt' => 'Chiều ngày 05/11/2025, Công ty Cổ phần Xi măng Cẩm Phả đã tổ chức Giải Pickleball mở rộng năm 2025 trong không khí tưng bừng, phấn khởi và tràn đầy năng lượng.',
            'content' => '<p>Chiều ngày 05/11/2025, Công ty Cổ phần Xi măng Cẩm Phả đã tổ chức Giải Pickleball mở rộng năm 2025 trong không khí tưng bừng, phấn khởi và tràn đầy năng lượng.</p><p>Giải đấu là dịp để cán bộ công nhân viên giao lưu, rèn luyện sức khỏe và tăng cường tinh thần đoàn kết.</p>',
            'image' => 'images/pickleball.webp',


            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-05',
            'is_featured' => true,
            'views' => 1250,
            'comments' => 5,
            'related_slugs' => ['khat-vong-tri-tue-ban-linh', 'vinh-danh-con-em-cbcnv'],
            'seo_title' => 'Giải Pickleball Xi Măng Cẩm Phả 2025',
            'seo_description' => 'Giải Pickleball mở rộng năm 2025 của Công ty Xi măng Cẩm Phả.',
        ],
        [
            'id' => 'n2',
            'slug' => 'khat-vong-tri-tue-ban-linh',
            'title' => 'Khát vọng – Trí tuệ – Bản lĩnh: Các tổ chức quần chúng Xi măng Cẩm Phả nhiệm kỳ 2025-2030',
            'excerpt' => 'Triển khai Chỉ thị số 1157-CT/ĐU, Công ty Cổ phần Xi măng Cẩm Phả (XMCP) đã tổ chức chuỗi Đại hội của "ba tổ chức quần chúng nòng cốt" tại đơn vị lần thứ IV',
            'content' => '<p>Triển khai Chỉ thị số 1157-CT/ĐU, Công ty Cổ phần Xi măng Cẩm Phả đã tổ chức chuỗi Đại hội của ba tổ chức quần chúng nòng cốt tại đơn vị lần thứ IV, nhiệm kỳ 2025-2030.</p>',
            'image' => 'https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=2070&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-10-10',
            'is_featured' => true,
            'views' => 890,
            'comments' => 3,
            'related_slugs' => ['giai-pickleball-mo-rong-2025', 'so-ket-quy-iii-2025'],
            'seo_title' => 'Khát vọng Trí tuệ Bản lĩnh - Xi Măng Cẩm Phả',
            'seo_description' => 'Đại hội các tổ chức quần chúng Xi măng Cẩm Phả nhiệm kỳ 2025-2030.',
        ],
        [
            'id' => 'n3',
            'slug' => 'vinh-danh-con-em-cbcnv',
            'title' => 'Lan tỏa niềm tự hào – Vinh danh con em CBCNV đạt thành tích học tập xuất sắc năm học 2025',
            'excerpt' => 'Trong không khí tưng bừng của cả nước hân hoan hướng tới kỷ niệm Quốc khánh 2/9 – ngày lễ trọng đại của dân tộc, vào 22/08/2025',
            'content' => '<p>Trong không khí tưng bừng của cả nước hân hoan hướng tới kỷ niệm Quốc khánh 2/9, vào ngày 22/08/2025, Công ty đã tổ chức lễ vinh danh con em CBCNV có thành tích học tập xuất sắc.</p>',
            'image' => 'https://images.unsplash.com/photo-1577896851231-70ef18881754?q=80&w=2070&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-08-22',
            'is_featured' => true,
            'views' => 670,
            'comments' => 2,
            'related_slugs' => ['giai-pickleball-mo-rong-2025', 'khat-vong-tri-tue-ban-linh'],
            'seo_title' => 'Vinh danh con em CBCNV - Xi Măng Cẩm Phả',
            'seo_description' => 'Vinh danh con em CBCNV đạt thành tích học tập xuất sắc năm 2025.',
        ],
        [
            'id' => 'n4',
            'slug' => 'so-ket-quy-iii-2025',
            'title' => 'Xi măng Cẩm Phả sơ kết Quý III năm 2025: Vững vàng ổn định – Tăng tốc về đích',
            'excerpt' => 'Ngày 08/11/2025, tại trụ sở chính Công ty Cổ phần Xi măng Cẩm Phả, Hội nghị sơ kết công tác sản xuất kinh doanh Quý III và triển khai nhiệm vụ Quý IV năm 2025',
            'content' => '<p>Ngày 08/11/2025, tại trụ sở chính Công ty Cổ phần Xi măng Cẩm Phả, Hội nghị sơ kết công tác sản xuất kinh doanh Quý III và triển khai nhiệm vụ Quý IV năm 2025 đã được tổ chức thành công.</p>',
            'image' => 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=2000&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-08',
            'is_featured' => true,
            'views' => 1100,
            'comments' => 4,
            'related_slugs' => ['khat-vong-tri-tue-ban-linh', 'vinh-danh-con-em-cbcnv'],
            'seo_title' => 'Sơ kết Quý III 2025 - Xi Măng Cẩm Phả',
            'seo_description' => 'Sơ kết Quý III 2025 - Xi Măng Cẩm Phả',
        ],
        [
            'id' => 'n5',
            'slug' => 'tuyen-dung-ky-su-dien-2025',
            'title' => 'Thông báo tuyển dụng Kỹ sư Điện hệ thống năm 2025',
            'excerpt' => 'Công ty Cổ phần Xi măng Cẩm Phả thông báo tuyển dụng vị trí Kỹ sư Điện hệ thống làm việc tại nhà máy Cẩm Phả.',
            'content' => '<p>Công ty Cổ phần Xi măng Cẩm Phả thông báo tuyển dụng vị trí Kỹ sư Điện hệ thống...</p>',
            'image' => 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=2070&auto=format&fit=crop',
            'category' => 'recruitment',
            'author' => 'Ban Nhân sự',
            'published_at' => '2025-11-01',
            'is_featured' => false,
            'views' => 450,
            'comments' => 0,
            'related_slugs' => [],
            'seo_title' => 'Tuyển dụng Kỹ sư Điện 2025 - Xi Măng Cẩm Phả',
            'seo_description' => 'Thông báo tuyển dụng Kỹ sư Điện hệ thống năm 2025.',
        ],
        [
            'id' => 'n6',
            'slug' => 'mock-article-6',
            'title' => 'Bài viết tin tức mẫu số 6 - Thêm nội dung để kiểm tra phân trang',
            'excerpt' => 'Đây là đoạn trích dẫn mẫu cho bài viết số 6. Đoạn trích này có thể hơi dài một chút để đảm bảo chức năng line-clamp 3 dòng hoạt động chính xác khi hiển thị trên thẻ.',
            'content' => '<p>Nội dung chi tiết cho bài viết số 6</p>',
            'image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f952?q=80&w=2070&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-06',
            'is_featured' => false,
            'views' => 120,
            'comments' => 1,
            'related_slugs' => [],
            'seo_title' => 'Bài viết mẫu 6',
            'seo_description' => 'Mô tả seo mẫu 6',
        ],
        [
            'id' => 'n7',
            'slug' => 'mock-article-7',
            'title' => 'Bài viết tin tức mẫu số 7 - Thêm nội dung để kiểm tra phân trang',
            'excerpt' => 'Đây là đoạn trích dẫn mẫu cho bài viết số 7. Đoạn trích này có thể hơi dài một chút để đảm bảo chức năng line-clamp 3 dòng hoạt động chính xác khi hiển thị trên thẻ.',
            'content' => '<p>Nội dung chi tiết cho bài viết số 7</p>',
            'image' => 'https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=2070&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-07',
            'is_featured' => false,
            'views' => 130,
            'comments' => 2,
            'related_slugs' => [],
            'seo_title' => 'Bài viết mẫu 7',
            'seo_description' => 'Mô tả seo mẫu 7',
        ],
        [
            'id' => 'n8',
            'slug' => 'mock-article-8',
            'title' => 'Bài viết tin tức mẫu số 8 - Thêm nội dung để kiểm tra phân trang',
            'excerpt' => 'Đây là đoạn trích dẫn mẫu cho bài viết số 8. Đoạn trích này có thể hơi dài một chút để đảm bảo chức năng line-clamp 3 dòng hoạt động chính xác khi hiển thị trên thẻ.',
            'content' => '<p>Nội dung chi tiết cho bài viết số 8</p>',
            'image' => 'https://images.unsplash.com/photo-1577896851231-70ef18881754?q=80&w=2070&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-08',
            'is_featured' => false,
            'views' => 140,
            'comments' => 3,
            'related_slugs' => [],
            'seo_title' => 'Bài viết mẫu 8',
            'seo_description' => 'Mô tả seo mẫu 8',
        ],
        [
            'id' => 'n9',
            'slug' => 'mock-article-9',
            'title' => 'Bài viết tin tức mẫu số 9 - Thêm nội dung để kiểm tra phân trang',
            'excerpt' => 'Đây là đoạn trích dẫn mẫu cho bài viết số 9. Đoạn trích này có thể hơi dài một chút để đảm bảo chức năng line-clamp 3 dòng hoạt động chính xác khi hiển thị trên thẻ.',
            'content' => '<p>Nội dung chi tiết cho bài viết số 9</p>',
            'image' => 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=2000&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-09',
            'is_featured' => false,
            'views' => 150,
            'comments' => 4,
            'related_slugs' => [],
            'seo_title' => 'Bài viết mẫu 9',
            'seo_description' => 'Mô tả seo mẫu 9',
        ],
        [
            'id' => 'n10',
            'slug' => 'mock-article-10',
            'title' => 'Bài viết tin tức mẫu số 10 - Thêm nội dung để kiểm tra phân trang',
            'excerpt' => 'Đây là đoạn trích dẫn mẫu cho bài viết số 10. Đoạn trích này có thể hơi dài một chút để đảm bảo chức năng line-clamp 3 dòng hoạt động chính xác khi hiển thị trên thẻ.',
            'content' => '<p>Nội dung chi tiết cho bài viết số 10</p>',
            'image' => 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=2070&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-10',
            'is_featured' => false,
            'views' => 160,
            'comments' => 5,
            'related_slugs' => [],
            'seo_title' => 'Bài viết mẫu 10',
            'seo_description' => 'Mô tả seo mẫu 10',
        ],
        [
            'id' => 'n11',
            'slug' => 'mock-article-11',
            'title' => 'Bài viết tin tức mẫu số 11 - Thêm nội dung để kiểm tra phân trang',
            'excerpt' => 'Đây là đoạn trích dẫn mẫu cho bài viết số 11. Đoạn trích này có thể hơi dài một chút để đảm bảo chức năng line-clamp 3 dòng hoạt động chính xác khi hiển thị trên thẻ.',
            'content' => '<p>Nội dung chi tiết cho bài viết số 11</p>',
            'image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f952?q=80&w=2070&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-11',
            'is_featured' => false,
            'views' => 170,
            'comments' => 6,
            'related_slugs' => [],
            'seo_title' => 'Bài viết mẫu 12',
            'seo_description' => 'Mô tả seo mẫu 12',
        ],
        [
            'id' => 'n13',
            'slug' => 'mock-article-13',
            'title' => 'Bài viết tin tức mẫu số 13 - Thêm nội dung để kiểm tra phân trang',
            'excerpt' => 'Đây là đoạn trích dẫn mẫu cho bài viết số 13. Đoạn trích này có thể hơi dài một chút để đảm bảo chức năng line-clamp 3 dòng hoạt động chính xác khi hiển thị trên thẻ.',
            'content' => '<p>Nội dung chi tiết cho bài viết số 13</p>',
            'image' => 'https://images.unsplash.com/photo-1577896851231-70ef18881754?q=80&w=2070&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-13',
            'is_featured' => false,
            'views' => 190,
            'comments' => 8,
            'related_slugs' => [],
            'seo_title' => 'Bài viết mẫu 13',
            'seo_description' => 'Mô tả seo mẫu 13',
        ],
        [
            'id' => 'n14',
            'slug' => 'mock-article-14',
            'title' => 'Bài viết tin tức mẫu số 14 - Thêm nội dung để kiểm tra phân trang',
            'excerpt' => 'Đây là đoạn trích dẫn mẫu cho bài viết số 14. Đoạn trích này có thể hơi dài một chút để đảm bảo chức năng line-clamp 3 dòng hoạt động chính xác khi hiển thị trên thẻ.',
            'content' => '<p>Nội dung chi tiết cho bài viết số 14</p>',
            'image' => 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=2000&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-14',
            'is_featured' => false,
            'views' => 200,
            'comments' => 9,
            'related_slugs' => [],
            'seo_title' => 'Bài viết mẫu 14',
            'seo_description' => 'Mô tả seo mẫu 14',
        ],
        [
            'id' => 'n15',
            'slug' => 'mock-article-15',
            'title' => 'Bài viết tin tức mẫu số 15 - Thêm nội dung để kiểm tra phân trang',
            'excerpt' => 'Đây là đoạn trích dẫn mẫu cho bài viết số 15. Đoạn trích này có thể hơi dài một chút để đảm bảo chức năng line-clamp 3 dòng hoạt động chính xác khi hiển thị trên thẻ.',
            'content' => '<p>Nội dung chi tiết cho bài viết số 15</p>',
            'image' => 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=2070&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-15',
            'is_featured' => false,
            'views' => 210,
            'comments' => 10,
            'related_slugs' => [],
            'seo_title' => 'Bài viết mẫu 15',
            'seo_description' => 'Mô tả seo mẫu 15',
        ],
        [
            'id' => 'n16',
            'slug' => 'mock-article-16',
            'title' => 'Bài viết tin tức mẫu số 16 - Thêm nội dung để kiểm tra phân trang',
            'excerpt' => 'Đây là đoạn trích dẫn mẫu cho bài viết số 16. Đoạn trích này có thể hơi dài một chút để đảm bảo chức năng line-clamp 3 dòng hoạt động chính xác khi hiển thị trên thẻ.',
            'content' => '<p>Nội dung chi tiết cho bài viết số 16</p>',
            'image' => 'https://images.unsplash.com/photo-1521737604893-d14cc237f952?q=80&w=2070&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-16',
            'is_featured' => false,
            'views' => 220,
            'comments' => 11,
            'related_slugs' => [],
            'seo_title' => 'Bài viết mẫu 16',
            'seo_description' => 'Mô tả seo mẫu 16',
        ],
        [
            'id' => 'n17',
            'slug' => 'mock-article-17',
            'title' => 'Bài viết tin tức mẫu số 17 - Thêm nội dung để kiểm tra phân trang',
            'excerpt' => 'Đây là đoạn trích dẫn mẫu cho bài viết số 17. Đoạn trích này có thể hơi dài một chút để đảm bảo chức năng line-clamp 3 dòng hoạt động chính xác khi hiển thị trên thẻ.',
            'content' => '<p>Nội dung chi tiết cho bài viết số 17</p>',
            'image' => 'https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=2070&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-17',
            'is_featured' => false,
            'views' => 230,
            'comments' => 12,
            'related_slugs' => [],
            'seo_title' => 'Bài viết mẫu 17',
            'seo_description' => 'Mô tả seo mẫu 17',
        ],
        [
            'id' => 'n18',
            'slug' => 'mock-article-18',
            'title' => 'Bài viết tin tức mẫu số 18 - Thêm nội dung để kiểm tra phân trang',
            'excerpt' => 'Đây là đoạn trích dẫn mẫu cho bài viết số 18. Đoạn trích này có thể hơi dài một chút để đảm bảo chức năng line-clamp 3 dòng hoạt động chính xác khi hiển thị trên thẻ.',
            'content' => '<p>Nội dung chi tiết cho bài viết số 18</p>',
            'image' => 'https://images.unsplash.com/photo-1577896851231-70ef18881754?q=80&w=2070&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-18',
            'is_featured' => false,
            'views' => 240,
            'comments' => 13,
            'related_slugs' => [],
            'seo_title' => 'Bài viết mẫu 18',
            'seo_description' => 'Mô tả seo mẫu 18',
        ],
        [
            'id' => 'n19',
            'slug' => 'mock-article-19',
            'title' => 'Bài viết tin tức mẫu số 19 - Thêm nội dung để kiểm tra phân trang',
            'excerpt' => 'Đây là đoạn trích dẫn mẫu cho bài viết số 19. Đoạn trích này có thể hơi dài một chút để đảm bảo chức năng line-clamp 3 dòng hoạt động chính xác khi hiển thị trên thẻ.',
            'content' => '<p>Nội dung chi tiết cho bài viết số 19</p>',
            'image' => 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?q=80&w=2000&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-19',
            'is_featured' => false,
            'views' => 250,
            'comments' => 14,
            'related_slugs' => [],
            'seo_title' => 'Bài viết mẫu 19',
            'seo_description' => 'Mô tả seo mẫu 19',
        ],
        [
            'id' => 'n20',
            'slug' => 'mock-article-20',
            'title' => 'Bài viết tin tức mẫu số 20 - Thêm nội dung để kiểm tra phân trang',
            'excerpt' => 'Đây là đoạn trích dẫn mẫu cho bài viết số 20. Đoạn trích này có thể hơi dài một chút để đảm bảo chức năng line-clamp 3 dòng hoạt động chính xác khi hiển thị trên thẻ.',
            'content' => '<p>Nội dung chi tiết cho bài viết số 20</p>',
            'image' => 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=2070&auto=format&fit=crop',
            'category' => 'company-activity',
            'author' => 'Ban Truyền thông',
            'published_at' => '2025-11-20',
            'is_featured' => false,
            'views' => 260,
            'comments' => 15,
            'related_slugs' => [],
            'seo_title' => 'Bài viết mẫu 20',
            'seo_description' => 'Mô tả seo mẫu 20',
        ],
    ],
];
