<?php

return [
    'products' => [
        [
            'id' => 1,
            'slug' => 'xi-mang-pcb30',
            'type' => 'cement',
            'title' => 'Xi măng PCB 30',
            'subtitle' => 'Giải pháp tối ưu cho xây trát và công trình dân dụng',
            'use_case' => 'Sử dụng cho các công trình dân dụng, xây tô và bê tông cường độ thấp',
            'image' => asset('images/pcb30.png'),

            'benefits' => [
                'Vữa dẻo siêu kết dính, dễ thi công',
                'Cường độ ổn định, phát triển nhanh',
                'Tiết kiệm chi phí vật liệu',
                'Phù hợp với khí hậu nhiệt đới Việt Nam',
            ],
            'advantages' => [
                [
                    'title' => 'Độ dẻo cao',
                    'content' => 'Giúp vữa bám dính tốt trên bề mặt gạch, đá, hạn chế rơi vãi và tạo bề mặt láng mịn.',
                ],
                [
                    'title' => 'Tiết kiệm chi phí',
                    'content' => 'Là lựa chọn kinh tế nhất cho các hạng mục xây trát và hoàn thiện công trình dân dụng.',
                ],
            ],
            'price_note' => 'Liên hệ Hotline để nhận báo giá chi tiết theo khu vực.',
            'related_slugs' => ['xi-mang-pcb40dd', 'xi-mang-xay-trat-cao-cap'],
            'seo_title' => 'Xi măng PCB 30 Cẩm Phả | Chất lượng cho mọi nhà',
            'seo_description' => 'Xi măng PCB 30 Cẩm Phả với độ dẻo cao, cường độ ổn định, là lựa chọn hàng đầu cho xây trát.',
        ],
        [
            'id' => 2,
            'slug' => 'xi-mang-pcb40cn',
            'type' => 'cement',
            'title' => 'Xi măng PCB 40CN',
            'subtitle' => 'Cường độ cao cho công trình công nghiệp và hạ tầng',
            'use_case' => 'Chuyên dùng cho cầu cống, đường giao thông, nhà xưởng công nghiệp',
            'image' => '/img/products/cement-set.png',
            'benefits' => [
                'Cường độ nén cao, chịu tải trọng lớn',
                'Tốc độ phát triển cường độ nhanh',
                'Chống xâm thực tốt trong môi trường kiềm',
                'Bền bỉ trước các tác động cơ học',
            ],
            'advantages' => [
                [
                    'title' => 'Cường độ vượt trội',
                    'content' => 'Đáp ứng các tiêu chuẩn khắt khe nhất của các công trình hạ tầng trọng điểm quốc gia.',
                ],
            ],
            'price_note' => 'Giá sản phẩm áp dụng cho dự án lớn và khách hàng doanh nghiệp.',
            'related_slugs' => ['xi-mang-pc50', 'xi-mang-xi-pcbbfs40'],
            'seo_title' => 'Xi măng PCB 40CN | Giải pháp cho hạ tầng bền vững',
            'seo_description' => 'Sản phẩm xi măng PCB 40CN Cẩm Phả chuyên dụng cho các hạng mục kết cấu chịu lực lớn.',
        ],
        [
            'id' => 3,
            'slug' => 'xi-mang-pc50',
            'type' => 'cement',
            'title' => 'Xi măng PC 50',
            'subtitle' => 'Đẳng cấp cho những công trình siêu trọng điểm',
            'use_case' => 'Nhà cao tầng, đập thủy điện, sân bay, cầu vượt biển',
            'image' => '/img/products/cement-set.png',
            'benefits' => [
                'Cường độ nén cực cao (trên 50 MPa)',
                'Hàm lượng khoáng C3S cao vượt trội',
                'Độ bền sunfat và chống ăn mòn hóa học tốt',
                'Nhanh tháo dỡ ván khuôn, đẩy nhanh tiến độ',
            ],
            'advantages' => [
                [
                    'title' => 'Chất lượng đặc biệt',
                    'content' => 'Được sản xuất theo quy trình kiểm soát nghiêm ngặt dành riêng cho các dự án đòi hỏi kỹ thuật cao.',
                ],
            ],
            'price_note' => 'Vui lòng liên hệ trực tiếp phòng kinh doanh để nhận báo giá dự án.',
            'related_slugs' => ['xi-mang-pcb40cn', 'clinker-cpc50'],
            'seo_title' => 'Xi măng PC 50 Cẩm Phả | Tiêu chuẩn kỹ thuật cao nhất',
            'seo_description' => 'Xi măng PC 50 Cẩm Phả đáp ứng yêu cầu của các công trình vĩnh cửu và trọng điểm quốc gia.',
        ],
        [
            'id' => 4,
            'slug' => 'xi-mang-pcb40dd',
            'type' => 'cement',
            'title' => 'Xi măng PCB 40DD',
            'subtitle' => 'Sản phẩm đa dụng cho mọi hạng mục công trình',
            'use_case' => 'Sử dụng cho cả đổ bê tông, xây tường và trát bề mặt',
            'image' => '/img/products/cement-set.png',
            'benefits' => [
                'Tính công tác tốt, vữa dẻo, bê tông đặc chắc',
                'Cường độ cao ổn định lâu dài',
                'Hạn chế rạn nứt bề mặt do co ngót',
                'Tiện lợi cho người sử dụng',
            ],
            'advantages' => [
                [
                    'title' => 'Sự lựa chọn đa năng',
                    'content' => 'Chỉ cần một loại xi măng cho toàn bộ công trình, từ móng đến mái, giúp quản lý vật tư dễ dàng hơn.',
                ],
            ],
            'price_note' => 'Giá bán lẻ đề nghị tại các cửa hàng đại lý trên toàn quốc.',
            'related_slugs' => ['xi-mang-pcb30', 'xi-mang-econs-40'],
            'seo_title' => 'Xi măng PCB 40DD Đa Dụng | Vững chắc mọi hạng mục',
            'seo_description' => 'Sản phẩm xi măng đa dụng Cẩm Phả mang lại sự yên tâm tuyệt đối cho chủ nhà.',
        ],
        [
            'id' => 5,
            'slug' => 'xi-mang-xi-pcbbfs40',
            'type' => 'cement',
            'title' => 'Xi măng xỉ PCBbfs40',
            'subtitle' => 'Bền bỉ vượt trội trong môi trường xâm thực',
            'use_case' => 'Công trình ven biển, đập nước, bê tông khối lớn',
            'image' => '/img/products/cement-set.png',
            'benefits' => [
                'Khả năng chống thấm cực tốt',
                'Chịu được nước mặn và môi trường phèn chua',
                'Nhiệt thủy hóa thấp, hạn chế nứt bê tông khối lớn',
                'Tăng tuổi thọ công trình lên đến hàng trăm năm',
            ],
            'advantages' => [
                [
                    'title' => 'Chống ăn mòn muối biển',
                    'content' => 'Thành phần xỉ lò cao giúp ngăn chặn sự xâm nhập của ion Chloride vào cốt thép.',
                ],
            ],
            'price_note' => 'Chuyên dụng cho các dự án xây dựng hạ tầng ven biển và đập thủy lợi.',
            'related_slugs' => ['xi-mang-xi-lo-cao', 'xi-mang-pcb40cn'],
            'seo_title' => 'Xi măng xỉ PCBbfs40 | Bảo vệ công trình ven biển',
            'seo_description' => 'Xi măng xỉ Cẩm Phả là giải pháp hàng đầu cho bê tông bền vững trong môi trường khắc nghiệt.',
        ],
        [
            'id' => 6,
            'slug' => 'xi-mang-econs-40',
            'type' => 'cement',
            'title' => 'Xi măng Econs 40',
            'subtitle' => 'Sự lựa chọn kinh tế và thân thiện môi trường',
            'use_case' => 'Dùng cho xây, tô, lát nền và trang trí nội ngoại thất',
            'image' => asset('images/econs40.webp'),

            'benefits' => [
                'Giảm phát thải CO2 trong quá trình sản xuất',
                'Độ mịn cao, bề mặt hoàn thiện láng mịn',
                'Vữa dẻo, dễ thi công, tiết kiệm thời gian',
                'Giá thành hợp lý, tối ưu chi phí đầu tư',
            ],
            'advantages' => [
                [
                    'title' => 'Xây dựng xanh',
                    'content' => 'Sản phẩm đạt tiêu chuẩn thân thiện với môi trường, góp phần bảo vệ hệ sinh thái.',
                ],
            ],
            'price_note' => 'Sản phẩm phổ biến tại thị trường nội địa với mức giá cạnh tranh.',
            'related_slugs' => ['xi-mang-pcb30', 'xi-mang-xay-trat-cao-cap'],
            'seo_title' => 'Xi măng Econs 40 | Kinh tế và Bền vững',
            'seo_description' => 'Dòng xi măng kinh tế của Cẩm Phả giúp tiết kiệm chi phí mà vẫn đảm bảo chất lượng.',
        ],
        [
            'id' => 7,
            'slug' => 'xi-mang-xay-trat-cao-cap',
            'type' => 'cement',
            'title' => 'Xi măng Xây trát cao cấp',
            'subtitle' => 'Chuyên dụng cho bề mặt tường láng mịn tuyệt đối',
            'use_case' => 'Tô trát tường trong và ngoài nhà, trang trí thẩm mỹ cao',
            'image' => asset('images/xaytrat.png'),

            'benefits' => [
                'Siêu dẻo, giữ nước cực lâu',
                'Hạn chế tối đa rạn nứt chân chim',
                'Tăng năng suất lao động cho thợ xây',
                'Bề mặt mịn màng, dễ sơn bả',
            ],
            'advantages' => [
                [
                    'title' => 'Khả năng giữ nước ưu việt',
                    'content' => 'Ngăn chặn hiện tượng mất nước đột ngột, giúp quá trình thủy hóa diễn ra hoàn toàn, chống nứt hiệu quả.',
                ],
            ],
            'price_note' => 'Sản phẩm cao cấp được tin dùng bởi các kiến trúc sư và nhà thầu uy tín.',
            'related_slugs' => ['xi-mang-pcb30', 'xi-mang-econs-40'],
            'seo_title' => 'Xi măng Xây trát cao cấp Cẩm Phả | Chống nứt chân chim',
            'seo_description' => 'Giải pháp chuyên dụng cho công tác hoàn thiện, mang lại vẻ đẹp hoàn mỹ cho công trình.',
        ],
        [
            'id' => 8,
            'slug' => 'xi-mang-xi-lo-cao',
            'type' => 'cement',
            'title' => 'Xi măng xỉ lò cao',
            'subtitle' => 'Phụ gia khoáng hoạt tính cho bê tông hiệu năng cao',
            'use_case' => 'Sản xuất bê tông cường độ cao, bê tông bền sunfat, bê tông tự đầm',
            'image' => '/img/products/clinker-raw.png',
            'benefits' => [
                'Tăng độ đặc chắc và khả năng chống thấm cho bê tông',
                'Cải thiện độ bền lâu dài, chống lại các tác nhân ăn mòn',
                'Giảm nhiệt thủy hóa, tránh nứt do nhiệt ở các khối bê tông lớn',
                'Tăng khả năng làm việc của hỗn hợp bê tông',
            ],
            'advantages' => [
                [
                    'title' => 'Bê tông thế hệ mới',
                    'content' => 'Sử dụng xỉ lò cao nghiền mịn giúp tạo ra các loại bê tông có tính năng đặc biệt mà xi măng thông thường không làm được.',
                ],
            ],
            'price_note' => 'Cung cấp dưới dạng rời cho các nhà máy sản xuất bê tông và trạm trộn.',
            'related_slugs' => ['xi-mang-xi-pcbbfs40', 'clinker-cpc50'],
            'seo_title' => 'Xi măng xỉ lò cao Cẩm Phả | Bê tông hiệu năng cao',
            'seo_description' => 'Sản phẩm chuyên biệt dành cho sản xuất bê tông tươi và bê tông đúc sẵn cao cấp.',
        ],
        [
            'id' => 9,
            'slug' => 'xi-mang-pcb40-jumbo',
            'type' => 'cement',
            'title' => 'Xi măng PCB40 đóng bao Jumbo 1,5 tấn',
            'subtitle' => 'Tiện lợi cho các trạm trộn và dự án quy mô lớn',
            'use_case' => 'Cung cấp cho trạm trộn bê tông tươi, công trình hạ tầng lớn',
            'image' => asset('images/pcb40-jumbo.png'),

            'benefits' => [
                'Chất lượng ổn định tương đương xi măng rời',
                'Quy cách đóng gói lớn giúp giảm hao hụt và chi phí bao bì',
                'Dễ dàng vận chuyển và lưu kho bằng xe nâng/cẩu',
                'Tiết kiệm nhân công bốc xếp',
            ],
            'advantages' => [
                [
                    'title' => 'Giải pháp cho dự án lớn',
                    'content' => 'Giúp đẩy nhanh tốc độ nạp liệu cho trạm trộn, đảm bảo cung ứng liên tục cho các công trình lớn.',
                ],
            ],
            'price_note' => 'Giá bán theo tấn, hỗ trợ giao hàng tận công trường bằng xe cẩu chuyên dụng.',
            'related_slugs' => ['xi-mang-pcb40cn', 'clinker-cpc50'],
            'seo_title' => 'Xi măng Bao Jumbo 1.5 Tấn Cẩm Phả | Giải pháp dự án',
            'seo_description' => 'Quy cách đóng gói hiện đại, đáp ứng nhu cầu thi công cường độ cao tại các đại dự án.',
        ],
        [
            'id' => 10,
            'slug' => 'clinker-cpc50',
            'type' => 'clinker',
            'title' => 'Clinker CPC 50',
            'subtitle' => 'Nguyên liệu cốt lõi đạt tiêu chuẩn quốc tế',
            'use_case' => 'Làm nguyên liệu chính để sản xuất các loại xi măng chất lượng cao',
            'image' => '/img/products/clinker-raw.png',
            'benefits' => [
                'Hàm lượng khoáng Alite (C3S) cao và ổn định',
                'Độ hoạt tính lớn, dễ nghiền, tiết kiệm năng lượng',
                'Thành phần hóa học đồng nhất, hàm lượng MgO thấp',
                'Đạt các tiêu chuẩn quốc tế ASTM (Mỹ) và EN (Châu Âu)',
            ],
            'advantages' => [
                [
                    'title' => 'Nguyên liệu xuất khẩu hàng đầu',
                    'content' => 'Clinker Cẩm Phả được tin dùng bởi nhiều nhà máy xi măng trên thế giới nhờ chất lượng ổn định và độ bền hóa học cao.',
                ],
            ],
            'price_note' => 'Liên hệ để nhận báo giá FOB/CIF cho thị trường xuất khẩu và báo giá nội địa.',
            'related_slugs' => ['xi-mang-pc50', 'xi-mang-xi-lo-cao'],
            'seo_title' => 'Clinker CPC 50 Cẩm Phả | Chất lượng quốc tế',
            'seo_description' => 'Nguyên liệu clinker chất lượng cao phục vụ sản xuất và xuất khẩu quốc tế.',
        ],
    ],
];
